#!/usr/bin/env python

import sys
import os
import re

from logging import handlers

from Bio import SeqIO

from bacteria2go.colorlog import ColorFormatter
from bacteria2go import __version__
from bacteria2go.utils import *

__author__ = "Marco Galardini"

def getOptions():
    import argparse

    # create the top-level parser
    description = "Extract the IGS spacer(s) from NCBI FTP genbanks"
    parser = argparse.ArgumentParser(description = description,
                                    prog = 'ftp2IGS')
    parser.add_argument('ftpdir', action='store',
                        help='FTP directory')        
    parser.add_argument('min', action='store', nargs='?',
                        default=None,
                        type=int,
                        help='IGS minimum length')
    parser.add_argument('max', action='store', nargs='?',
                        default=None,
                        type=int,
                        help='IGS maximum length')

    parser.add_argument('--working-dir', action='store',
                        default='.',
                        dest='wdir',
                        help='Working directory')
    parser.add_argument('-v', action='count',
                        default=0,
                        help='Increase verbosity level')
    parser.add_argument('--version', action='version',
                        version='%(prog)s '+__version__)

    return parser.parse_args()
    
if __name__ == "__main__":
    options = getOptions()

    # Log setup
    logger = logging.getLogger()

    ch = logging.StreamHandler()
    if options.v == 0:
        ch.setLevel(logging.INFO)
    elif options.v >= 1:
        ch.setLevel(logging.DEBUG)
    formatter = ColorFormatter('%(asctime)s - $COLOR%(message)s$RESET','%H:%M:%S')
    ch.setFormatter(formatter)
    logger.addHandler(ch)

    logger.setLevel(logging.DEBUG)

    fh = handlers.RotatingFileHandler('ftp2IGS.log', maxBytes=2000000)
    formatter = logging.Formatter('%(asctime)s - %(name)s - [%(levelname)s] - %(message)s',
                            '%Y-%m-%d %H:%M:%S')
    fh.setFormatter(formatter)
    logger.addHandler(fh)
   
    # Start
    # rRNA magic regex
    regex = '(.*)16[sS]|(.*)23[sS]'    
    prog = re.compile(regex)

    logger.info('Using /%s/ regex search'%regex)
    
    logger.info('Extracting IGS from %s'%(options.ftpdir))

    ftpdir = options.ftpdir
    logger.info('Genomes w/ no IGS will be written to %s'%
                os.path.join(options.wdir, 'notfound.txt'))
    notf = open(os.path.join(options.wdir, 'notfound.txt'), 'w')
    
    for d in os.listdir(ftpdir):
        dpath = os.path.join(ftpdir, d)
        if not os.path.isdir(dpath):
            continue
    
        # We use the uid as species name
        org = d.split('uid')[-1]

        i = 0
        rseqs = []

        for fgbk in filter(lambda x: x.endswith('.gbk'),
                        os.listdir(dpath)):
            fpath = os.path.join(dpath, fgbk)
            
            logger.debug('Reading %s'%fgbk)
            for s in SeqIO.parse(fpath, 'genbank'):
                rRNA = sorted(filter(lambda x: x.type == 'rRNA', s.features),
                              key=lambda x: int(x.location.start))
                for f, f1 in zip(rRNA, rRNA[1:]):
                    # Are we between 16s and 23s?
                    if (not prog.match(f.qualifiers['product'][0]) or
                        not prog.match(f1.qualifiers['product'][0])):
                        continue
                
                    # We suppose they should be in the same strand, right?
                    if f.strand != f1.strand:
                        continue
                
                    # Check that the two features are not so distant from each other
                    dist = int(f1.location.start) - int(f.location.end)
                    if options.min is not None and options.max is not None:
                        if dist > options.max or dist < options.min:
                            logger.warning('Discarding IGS based on length constraints')
                            continue     
                
                    i += 1
                    rid = '%s_%d'%(org, i)
            
                    rseq = s[int(f.location.end)+1: int(f1.location.start)-1]
                    if f.strand < 0:
                        rseq = rseq.reverse_complement()
                        rseq.description = '(%s, %d, %d, -)'%(s.id,
                            int(f.location.end)+1, int(f1.location.start)-1)
                    else:
                        rseq.description = '(%s, %d, %d, +)'%(s.id,
                            int(f.location.end)+1, int(f1.location.start)-1)    
                    rseq.id = rid

                    if 'N' in rseq.seq:
                        logger.warning('N nucleotide found, skipping this sequence')
                        i -= 1
                        continue
            
                    rseqs.append(rseq)
            
        if len(rseqs) == 0:
            logger.warning('No IGS found for %s'%d)
            notf.write('%s\n'%d)
            continue
    
        logger.info('Found %d IGS in %s'%(len(rseqs), d))
        fout = os.path.join(options.wdir, '%s.igs.fna'%d)
        SeqIO.write(rseqs, fout, 'fasta')

    notf.close()
