#!/usr/bin/env python

import sys

if len(sys.argv) < 2:
    print('USAGE: oma2tsv OMA_OGs')
    sys.exit(1)

infile = sys.argv[1]

orgs = set()
d = {}

f = open('pangenome.tsv', 'w')
f.write('#')
f.write('\t'.join(['orth_id', 'prot_id', 'org_id']))
f.write('\n')

for l in open(infile):
    l = l.strip()
    if l.startswith('#'):
        continue
    
    s = l.split('\t')

    orth_id = s[0]
    orgs_prots = s[1:]

    for op in orgs_prots:
        o = op.split(':')[0]
        p = op.split(':')[1].split()[0]
        f.write('\t'.join([orth_id, p, o]))
        f.write('\n')

        orgs.add(o)
        d[orth_id] = d.get(orth_id, set())
        d[orth_id].add( o )

f.close()

nc = len(orgs)

f = open('pangenome_category.tsv', 'w')
f.write('\t'.join(['orth_id', 'category', 'org(s)']))
f.write('\n')

# Core
for k in filter(lambda x: len(d[x]) == nc, d):
    f.write('\t'.join([k, 'core', '\t'.join(sorted(d[k]))]))
    f.write('\t')

# Accessory
for k in filter(lambda x: len(d[x]) < nc and len(d[x]) > 1, d):
    f.write('\t'.join([k, 'accessory', '\t'.join(sorted(d[k]))]))
    f.write('\n')

# Unique
for k in filter(lambda x: len(d[x]) == 1, d):
    f.write('\t'.join([k, 'unique', '\t'.join(sorted(d[k]))]))
    f.write('\n')

f.close()
